name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run: go install github.com/praetorian-inc/gokart@latest
    - name: Get rule
      run: go install -v github.com/quasilyte/go-ruleguard/cmd/ruleguard@latest

    - name: Test code
      run: gokart scan
    - name: rule code
      run: ruleguard -rules rules.go -fix main.go

